[bumpver]
current_version = "0.1.8"
version_pattern = "MAJOR.MINOR.PATCH"

[bumpver.file_patterns]
"setup.py" = [
    "version=\"{version}\",",
]
"src/moralis/__init__.py" = [
    "^__version__ = \"{version}\"$",
]

