name: Generate

on:
  schedule:
    # Runs “At 5th minute.” (see https://crontab.guru)
    - cron: '*/5 * * * *'
  push:
    branches:
      - main

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip requests
      - name: 'Generate 1: prepare input files'
        run: 'python scripts/generate_ci_1.py'

      - name: 'Generate 2.1 OpenApi for EvmApi'
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python
          config-file: openapi.json
          openapi-file: temp/swagger/evm_api.json
          command-args: '-o temp/generated-api -p packageName=openapi_evm_api,projectName=evm_api'

      - name: 'Generate 2.2 OpenApi for SolApi'
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python
          config-file: openapi.json
          openapi-file: temp/swagger/sol_api.json
          command-args: '-o temp/generated-api -p packageName=openapi_sol_api,projectName=sol_api'

      - name: 'Generate 2.3 OpenApi for Auth'
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python
          config-file: openapi.json
          openapi-file: temp/swagger/auth.json
          command-args: '-o temp/generated-api -p packageName=openapi_auth,projectName=auth'

      - name: 'Generate 2.4 OpenApi for Streams'
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python
          config-file: openapi.json
          openapi-file: temp/swagger/streams.json
          command-args: '-o temp/generated-api -p packageName=openapi_streams,projectName=streams'

      # Make sure we can access the generated packages in the next step
      - name: Install Python local dependency
        run: |
          pip install -e .

      - name: 'Generate 3: generate output files'
        run: 'python scripts/generate_ci_2.py'

      - name: "File changes detected: Create PR"
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            src/**/*
            docs/**/*
          commit-message: 'fix: automatic api update'
          committer: 'Moralis CI/CD <noreply@github.com>'
          branch: generate
          base: main
          title: 'Update SDK'
          body: |
            This PR was automatically opened via Github Actions.

            New Api changes have been detected. To release:

            1. Make any manual changes that are needed
            2. Merge this PR to `main`
            3. Wait for the next Github Action to do an automatic release

            **Note that this PR is automatically updated when more changes are made to the APIs.**
          labels: 'Automated PR'
          team-reviewers: |
            owners
            maintainers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



