name: Generate

on:
  schedule:
    # Runs "At every 30th minute" (see https://crontab.guru)
    - cron: "*/30 * * * *"
  push:
    branches:
      - main

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v4
      - name: "Generate 1/2"
        run: "python scripts/generate_ci_1.py"
      # Make sure we can access the generated packages in the next step
      - name: Install Python local dependency
        run: |
          pip install -e .
      - name: "Generate 2/2"
        run: "python scripts/generate_ci_2.py"
      - name: "File changes detected: Create PR"
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            src/**/*
            docs/**/*
          commit-message: "fix: automatic api update"
          committer: "Moralis CI/CD <noreply@github.com>"
          branch: generate
          base: main
          title: "Update SDK"
          body: |
            This PR was automatically opened via Github Actions.

            New Api changes have been detected. To release:

            1. Make any manual changes that are needed
            2. Merge this PR to `main`
            3. Wait for the next Github Action to do an automatic release

            **Note that this PR is automatically updated when more changes are made to the APIs.**
          labels: "Automated PR"
          team-reviewers: |
            owners
            maintainers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
